
-- CREATING a new table
CREATE TABLE EMPLOYEE(
    Id INT  NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    Name VARCHAR(255) NOT NULL,
    Age INT NOT NULL,
    Designation VARCHAR(255) NOT NULL
);


-- creating a table from existing table
CREATE TABLE NEW AS
  SELECT * 
  FROM EMPLOYEE;

-- DEFINING PRIMARY AND FOREIGN KEY 

CREATE TABLE DEPARTMENT (
    dept_id INT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE EMPLOYEES (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    dept_id INT, 
    FOREIGN KEY (dept_id) REFERENCES DEPARTMENT(dept_id)
);

